version: '3.1'

services:
  db:
    image: postgres:14.7
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
    networks:
      - mynetwork
  app:
    build: .
    ports:
      - "80:5000"
    depends_on:
      - db
    networks:
      - mynetwork
networks:
  mynetwork:
