"""empty message

Revision ID: ec8d0c2ba70c
Revises: 
Create Date: 2023-07-02 15:54:17.390888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec8d0c2ba70c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_feed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('web_resource',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('protocol', sa.String(length=10), nullable=True),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('domain_zone', sa.String(length=10), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('path', sa.String(length=100), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('screenshot', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('web_resource')
    op.drop_table('news_feed')
    # ### end Alembic commands ###
